name = "WaveSimulator"
uuid = "54d19186-ca7e-551c-8089-2d7959022c57"
version = "0.1.0"

[deps]
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
ValueHistories = "98cad3c8-aec3-5f06-8e41-884608649ab7"
